import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'nav.home': '首頁',
    'nav.about': '關於我們',
    'nav.products': '產品中心',
    'nav.solutions': '解決方案',
    'nav.cases': '成功案例',
    'nav.contact': '聯絡我們',
    'brand.name': '特來電香港',
    'footer.desc': '致力於成為中國最強的新能源汽車充電網生態運營公司。圍繞國家新基建戰略部署——穩步推進國際化。',
    'footer.quickLinks': '快速連結',
    'footer.contact': '聯絡資訊',
    'footer.company': '特來智慧能源香港有限公司',
    'home.hero.title1': '引領全球充電網生態',
    'home.hero.title2': '共創綠色能源未來',
    'home.hero.desc': '致力成為中國最強的新能源汽車充電網生態運營公司。圍繞國家新基建戰略部署——穩步推進國際化。',
    'home.hero.btn.products': '查看產品',
    'home.hero.btn.contact': '聯絡我們',
    'home.video.unsupported': '您的瀏覽器不支援影片播放。',
    'home.why.title': '為什麼選擇特來電?',
    'home.why.desc': '特來電是世界充電網技術體系開創者和引領者，研發投入超過20億元。',
    'home.stat.cities': '覆蓋城市',
    'home.stat.cities.value': '360+',
    'home.stat.piles': '充電樁',
    'home.stat.piles.value': '58萬+',
    'home.stat.market': '市場佔有率',
    'home.stat.market.value': '42',
    'home.stat.market.unit': '%',
    'home.stat.users': '註冊用戶',
    'home.stat.users.value': '3000萬+',
    'home.feature1.title': '數量世界第一',
    'home.feature1.desc': 'No.1 in Quantity and Market Presence. 覆蓋360個城市，充電樁58萬個。',
    'home.feature2.title': '電量行業第一',
    'home.feature2.desc': 'No.1 in EV Electricity Charging. 累計充電量300億度，市場佔有率42%。',
    'home.feature3.title': '技術國際領先',
    'home.feature3.desc': 'International advanced technology. 研發投入20億元，擁有最大充電工業互聯網大數據。',
    'home.partners.title': '全球戰略合作夥伴',
    'home.cta.title': '準備好開始您的綠色能源之旅了嗎？',
    'home.cta.desc': '無論是政府規劃、企業園區還是個人安裝，特來電都能為您提供最專業的解決方案。',
    'home.cta.btn': '立即聯絡我們',
    'about.title': '關於特來電',
    'about.desc': '特來電致力成為中國最強的新能源汽車充電網生態運營公司，專業從事電動汽車充放電設備的設計、研發、生產、施工及服務等工作。作為國內新能源充電領域的龍頭企業，我們擁有強大的技術實力與深厚的行業經驗，積極響應國家戰略，與國家電網等機構展開深度合作。同時，特來電也是大灣區中電（CLP）的重要合作夥伴，強強聯手，共同推動粵港澳大灣區綠色交通與智慧能源的蓬勃發展。',
    'about.overview.title': '公司概況',
    'about.overview.p1': '公司自成立之初就堅持「一步領先、步步領先」的創新領航戰略，致力於電力電子技術的研發，現已掌握數百項知識產權，涵蓋電動汽車群智能充電技術、光儲充放一體化技術、新型微電網技術、大功率自動充電技術等方向。',
    'about.overview.p2': '其中「電動汽車群智能充電系統」以「無樁充電、無電插頭、群管群控、模塊結構、主動防護、柔性充電」的特點引領世界新能源汽車充電的發展，被國內專家團鑒定為「產品世界首創、技術水平國際領先」。',
    'about.overview.p3': '「充電網兩層防護技術」的應用為電動汽車充電上了一把「安全鎖」，在充電過程中對汽車的安全隱患做到了可監視、可預警、可控制、可追溯，有效降低燒車事故，被國內頂級專家全面鑒定為「世界領先」。',
    'about.tech.title': '技術創新與未來展望',
    'about.tech.p1': '特來電不僅在充電技術上持續突破，更積極佈局「充電網+微電網+儲能網」的三網融合體系。通過大數據分析與AI智能調度，實現能源的高效利用與電網的友好互動。',
    'about.tech.p2': '未來，特來電將繼續深耕新能源領域，推動交通電動化與能源數字化的深度融合，為全球碳中和目標貢獻中國智慧與中國方案。',
    'about.mission.title': '特來電使命',
    'about.mission.quote': '"實現新能源車充新能源電，讓尾氣和霧霾遠離人類"',
    'about.mission.en': 'Power electric vehicles with renewable electricity, and protect humans from exhaust gas and smog.',
    'about.mission.item1': '成為新能源革命的引領者',
    'about.mission.item2': '做政府放心、客戶滿意的中國最強汽車充電網生態運營公司',
    'about.mission.item3': '以客戶至上、以人為本的價值觀',
    'about.mission.item4': '構建可持續發展的綠色能源生態系統',
    'contact.title': '聯絡我們',
    'contact.desc': '如有任何疑問或合作意向，歡迎隨時與我們聯繫',
    'contact.info.title': '聯繫方式',
    'contact.info.phone': '電話',
    'contact.info.phone.desc': '週一至週五 9:00 - 18:00',
    'contact.info.whatsapp': 'WhatsApp',
    'contact.info.whatsapp.desc': '點擊直接發送訊息',
    'contact.info.facebook': 'Facebook',
    'contact.info.facebook.desc': '關注我們的最新動態',
    'contact.info.email': '電子郵件',
    'contact.info.email.desc': '我們將在24小時內回覆您的郵件',
    'contact.form.title': '發送訊息',
    'contact.form.name': '姓名',
    'contact.form.name.placeholder': '您的姓名',
    'contact.form.phone': '電話',
    'contact.form.phone.placeholder': '您的聯絡電話',
    'contact.form.email': '電子郵件',
    'contact.form.email.placeholder': '您的電子郵件',
    'contact.form.message': '訊息內容',
    'contact.form.message.placeholder': '請輸入您的需求或問題...',
    'contact.form.submit': '發送訊息',
    'contact.form.subject': '來自 {name} 的網站留言',
    'contact.form.body': '姓名: {name}\n電話: {phone}\n電子郵件: {email}\n\n訊息內容:\n{message}',
    'solutions.title': '充電網解決方案',
    'solutions.desc': '充電網是電動汽車規模化發展的基礎支撐。特來電通過充電網與配電網並行，融合互補，調度協同，構建生態充電網。',
    'solutions.bus.title': '公交充電網',
    'solutions.bus.desc': '有序充電，降本增效，支持對外復用；平台互聯互通，定制安全防護報告；靈活迭代微電網，退役電池再利用。',
    'solutions.public.title': '公共充電網',
    'solutions.public.desc': '功率靈活調度，提升場站周轉率；智能運維、特慧看AI安全預警；數智化場站，充電便捷高效。',
    'solutions.logistics.title': '物流充電網',
    'solutions.logistics.desc': '平台互聯互通，提升運行效率；靈活接入光伏，新能源就地消納；全場景自動充電解決方案。',
    'solutions.enterprise.title': '企業園區充電網',
    'solutions.enterprise.desc': '低谷充電，降低用能成本；有序充電，不和居民搶電；兩層安全防護保駕護航。',
    'solutions.residential.title': '住宅屋苑充電網',
    'solutions.residential.desc': '有序共享，開車滿電；園區微電網節能增效；升級V2G，參與電網互動。',
    'solutions.arch.title': '如何構建生態充電網?',
    'solutions.arch.step1.title': '頂層設計，做好城市充電網規劃',
    'solutions.arch.step1.item1': '1. 政策 (Policy)',
    'solutions.arch.step1.item2': '2. 標準 (Standard)',
    'solutions.arch.step1.item3': '3. 規範 (Criterion)',
    'solutions.arch.step1.item4': '4. 供電 (Power Supply)',
    'solutions.arch.step1.item5': '5. 投資 (Investment)',
    'solutions.arch.step2.title': '智慧選址，合理布局',
    'solutions.arch.step2.desc': '依托特來電運營數據庫，自動研判競爭態勢。根據後台大數據計算，劃定3公里“六邊形”熱力區，根據熱力區顏色即可判斷競爭情況。',
    'solutions.arch.step2.comp': '競爭',
    'solutions.arch.step2.elec': '電量',
    'solutions.arch.step2.analysis': '熱力分析',
    'cases.title': '成功案例',
    'cases.desc': '特來電在全國360+城市及海外多個國家擁有豐富的運營經驗和應用案例',
    'cases.tab.hongkong': '香港',
    'cases.tab.domestic': '國內案例',
    'cases.tab.international': '國外案例',
    'cases.btn.details': '查看詳情',
    'cases.modal.charging': '充電設施',
    'cases.modal.energy': '節能效益',
    'cases.modal.feedback': '客戶回饋',
    'cases.partners.title': '合作客戶',
    'cases.partners.subtitle': '服務全球用戶1200餘家',
    'cases.partners.desc': '公司為全球眾多企業客戶提供精緻產品和優質服務，涵蓋政府、央企、公交、機場、港口、地產、商用車、商業綜合體、企事業園區、海外等多種領域。',
    'cases.partners.target.title': '特來電希望對接的合作伙伴',
    'cases.partners.target.1': '面向有志於發展新能源充電產業的政府及公共投資平台',
    'cases.partners.target.2': '面向向新能源轉型的傳統能源公司',
    'cases.partners.target.3': '面向想要成為充電運營商的投資公司或企業',
    'cases.partners.target.4': '面向有渠道資源且想要發展成為充電樁代理商的伙伴',
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.products': 'Products',
    'nav.solutions': 'Solutions',
    'nav.cases': 'Cases',
    'nav.contact': 'Contact Us',
    'brand.name': 'TELD HK',
    'footer.desc': 'Committed to becoming China\'s strongest new energy vehicle charging network ecological operation company. Centered around the national new infrastructure strategy—steadily advancing internationalization.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact Info',
    'footer.company': 'TELD Intelligent Energy Hong Kong Limited',
    'home.hero.title1': 'Leading Global Charging Network',
    'home.hero.title2': 'Co-creating a Green Energy Future',
    'home.hero.desc': 'Committed to becoming China\'s strongest new energy vehicle charging network ecological operation company. Centered around the national new infrastructure strategy—steadily advancing internationalization.',
    'home.hero.btn.products': 'View Products',
    'home.hero.btn.contact': 'Contact Us',
    'home.video.unsupported': 'Your browser does not support video playback.',
    'home.why.title': 'Why Choose TELD?',
    'home.why.desc': 'TELD is the pioneer and leader of the world\'s charging network technology system, with R&D investment exceeding 2 billion RMB.',
    'home.stat.cities': 'Cities Covered',
    'home.stat.cities.value': '360+',
    'home.stat.piles': 'Charging Piles',
    'home.stat.piles.value': '580k+',
    'home.stat.market': 'Market Share',
    'home.stat.market.value': '42',
    'home.stat.market.unit': '%',
    'home.stat.users': 'Registered Users',
    'home.stat.users.value': '30M+',
    'home.feature1.title': 'No.1 in Quantity',
    'home.feature1.desc': 'No.1 in Quantity and Market Presence. Covering 360 cities with 580,000 charging piles.',
    'home.feature2.title': 'No.1 in Electricity',
    'home.feature2.desc': 'No.1 in EV Electricity Charging. Cumulative charging volume of 30 billion degrees, 42% market share.',
    'home.feature3.title': 'Leading Technology',
    'home.feature3.desc': 'International advanced technology. R&D investment of 2 billion RMB, possessing the largest charging industrial internet big data.',
    'home.partners.title': 'Global Strategic Partners',
    'home.cta.title': 'Ready to start your green energy journey?',
    'home.cta.desc': 'Whether it\'s government planning, corporate parks, or personal installation, TELD can provide you with the most professional solutions.',
    'home.cta.btn': 'Contact Us Now',
    'about.title': 'About TELD',
    'about.desc': 'TELD is committed to becoming China\'s strongest new energy vehicle charging network ecological operation company, specializing in the design, R&D, production, construction, and services of EV charging and discharging equipment. As a leading enterprise in the domestic new energy charging field, we have strong technical strength and deep industry experience, actively responding to national strategies and conducting deep cooperation with institutions like the State Grid. Meanwhile, TELD is also an important partner of CLP in the Greater Bay Area, joining forces to promote the vigorous development of green transportation and smart energy in the Guangdong-Hong Kong-Macao Greater Bay Area.',
    'about.overview.title': 'Company Overview',
    'about.overview.p1': 'Since its inception, the company has adhered to the innovative leading strategy of "one step ahead, step by step ahead", committed to the R&D of power electronics technology, and has mastered hundreds of intellectual property rights, covering EV group smart charging technology, optical storage charging and discharging integration technology, new microgrid technology, high-power automatic charging technology, etc.',
    'about.overview.p2': 'Among them, the "EV Group Smart Charging System" leads the development of world new energy vehicle charging with the characteristics of "no pile charging, no electric plug, group management and control, modular structure, active protection, flexible charging", and is appraised by the domestic expert group as "the world\'s first product, international leading technical level".',
    'about.overview.p3': 'The application of "Charging Network Two-layer Protection Technology" has put a "safety lock" on EV charging, achieving monitorable, early warning, controllable, and traceable safety hazards of vehicles during charging, effectively reducing car burning accidents, and comprehensively appraised by top domestic experts as "world leading".',
    'about.tech.title': 'Technological Innovation and Future Outlook',
    'about.tech.p1': 'TELD not only continues to break through in charging technology, but also actively lays out the three-network integration system of "charging network + microgrid + energy storage network". Through big data analysis and AI intelligent scheduling, it achieves efficient energy utilization and friendly interaction with the power grid.',
    'about.tech.p2': 'In the future, TELD will continue to deepen the new energy field, promote the deep integration of transportation electrification and energy digitization, and contribute Chinese wisdom and Chinese solutions to the global carbon neutrality goal.',
    'about.mission.title': 'TELD Mission',
    'about.mission.quote': '"Power electric vehicles with renewable electricity, and protect humans from exhaust gas and smog."',
    'about.mission.en': 'Power electric vehicles with renewable electricity, and protect humans from exhaust gas and smog.',
    'about.mission.item1': 'Become a leader in the new energy revolution',
    'about.mission.item2': 'Be the strongest EV charging network ecological operation company in China that the government trusts and customers are satisfied with',
    'about.mission.item3': 'Customer-first, people-oriented values',
    'about.mission.item4': 'Build a sustainable green energy ecosystem',
    'contact.title': 'Contact Us',
    'contact.desc': 'If you have any questions or cooperation intentions, please feel free to contact us',
    'contact.info.title': 'Contact Information',
    'contact.info.phone': 'Phone',
    'contact.info.phone.desc': 'Mon-Fri 9:00 - 18:00',
    'contact.info.whatsapp': 'WhatsApp',
    'contact.info.whatsapp.desc': 'Click to send message directly',
    'contact.info.facebook': 'Facebook',
    'contact.info.facebook.desc': 'Follow our latest updates',
    'contact.info.email': 'Email',
    'contact.info.email.desc': 'We will reply to your email within 24 hours',
    'contact.form.title': 'Send Message',
    'contact.form.name': 'Name',
    'contact.form.name.placeholder': 'Your Name',
    'contact.form.phone': 'Phone',
    'contact.form.phone.placeholder': 'Your Phone Number',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'Your Email',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Please enter your needs or questions...',
    'contact.form.submit': 'Send Message',
    'contact.form.subject': 'Website message from {name}',
    'contact.form.body': 'Name: {name}\nPhone: {phone}\nEmail: {email}\n\nMessage:\n{message}',
    'solutions.title': 'Charging Network Solutions',
    'solutions.desc': 'The charging network is the basic support for the large-scale development of electric vehicles. TELD builds an ecological charging network through the parallel, integrated, complementary, and coordinated dispatch of the charging network and the distribution network.',
    'solutions.bus.title': 'Bus Charging Network',
    'solutions.bus.desc': 'Orderly charging, reducing costs and increasing efficiency, supporting external reuse; platform interconnection, customized safety protection reports; flexible iteration of microgrids, retired battery reuse.',
    'solutions.public.title': 'Public Charging Network',
    'solutions.public.desc': 'Flexible power dispatching, improving station turnover rate; intelligent operation and maintenance, TELD AI safety warning; digital intelligent stations, convenient and efficient charging.',
    'solutions.logistics.title': 'Logistics Charging Network',
    'solutions.logistics.desc': 'Platform interconnection, improving operational efficiency; flexible access to photovoltaics, local consumption of new energy; full-scenario automatic charging solutions.',
    'solutions.enterprise.title': 'Enterprise Park Charging Network',
    'solutions.enterprise.desc': 'Valley charging, reducing energy costs; orderly charging, not competing with residents for electricity; two-layer safety protection escort.',
    'solutions.residential.title': 'Residential Charging Network',
    'solutions.residential.desc': 'Orderly sharing, driving with full power; park microgrid energy saving and efficiency enhancement; upgrading V2G, participating in grid interaction.',
    'solutions.arch.title': 'How to build an ecological charging network?',
    'solutions.arch.step1.title': 'Top-level design, do a good job in urban charging network planning',
    'solutions.arch.step1.item1': '1. Policy',
    'solutions.arch.step1.item2': '2. Standard',
    'solutions.arch.step1.item3': '3. Criterion',
    'solutions.arch.step1.item4': '4. Power Supply',
    'solutions.arch.step1.item5': '5. Investment',
    'solutions.arch.step2.title': 'Smart site selection, reasonable layout',
    'solutions.arch.step2.desc': 'Relying on TELD operation database, automatically judge the competitive situation. According to the background big data calculation, delineate a 3-kilometer "hexagonal" thermal area, and judge the competition according to the color of the thermal area.',
    'solutions.arch.step2.comp': 'Competition',
    'solutions.arch.step2.elec': 'Electricity',
    'solutions.arch.step2.analysis': 'Thermal Analysis',
    'cases.title': 'Successful Cases',
    'cases.desc': 'TELD has rich operational experience and application cases in 360+ cities nationwide and multiple countries overseas',
    'cases.tab.hongkong': 'Hong Kong',
    'cases.tab.domestic': 'Domestic Cases',
    'cases.tab.international': 'International Cases',
    'cases.btn.details': 'View Details',
    'cases.modal.charging': 'Charging Facilities',
    'cases.modal.energy': 'Energy Saving Benefits',
    'cases.modal.feedback': 'Customer Feedback',
    'cases.partners.title': 'Partner Clients',
    'cases.partners.subtitle': 'Serving over 1200 global users',
    'cases.partners.desc': 'The company provides exquisite products and high-quality services to many corporate clients worldwide, covering government, state-owned enterprises, public transportation, airports, ports, real estate, commercial vehicles, commercial complexes, enterprise parks, overseas, and other fields.',
    'cases.partners.target.title': 'Partners TELD hopes to connect with',
    'cases.partners.target.1': 'Government and public investment platforms interested in developing the new energy charging industry',
    'cases.partners.target.2': 'Traditional energy companies transitioning to new energy',
    'cases.partners.target.3': 'Investment companies or enterprises wanting to become charging operators',
    'cases.partners.target.4': 'Partners with channel resources who want to develop into charging pile agents',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
